# Generated by Django 4.2.20 on 2025-05-19 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('academico', 'Académico'), ('admision', 'Admisión'), ('financiero', 'Financiero')], default='academico', max_length=20),
        ),
    ]
