# Generated by Django 4.2.20 on 2025-05-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_area_escuela_alter_user_area_alter_user_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.escuela')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.carrera'),
        ),
    ]
